### ISSUE TITLE
Can't get content of <link> element

### ISSUE THREAD

**Issue by ghost** [kostya/modest#3]
In the following program and XML file, the content for `<title>` comes through successfully, but not for `<link>`. Interestingly, when I change `<link>` to `<url>` and update the Crystal code accordingly, the content does print successfully, so I'm only having an issue getting content inside of a `<link>` node.

### app.cr
```crystal
require "myhtml"
require "modest"

page = File.read("./test.xml")
myhtml = Myhtml::Parser.new(page)
items = myhtml.css("item")
items.each do |item|
	puts "Title: #{item.css("title").first.inner_text}"
	puts "Link: #{item.css("link").first.inner_text}"
end
```

### test.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<items>
  <item>
    <title>My title</title>
    <link>https://myurl.com</link>
  </item>
</items>
```

**Comment by kostya** [comment]
Not sure, should this work or not, because it not xml parser. link is parsed as https://www.w3schools.com/tags/tag_link.asp. `Note: The <link> element is an empty element, it contains attributes only.`. Any way you can ask it in engine repo:  https://github.com/lexborisov/Modest
